[package]
name = "advent_code_2022"
version = "0.1.0"
edition = "2021"
default-run = "advent_code_2022"

[[bin]]
name = "day_1"
path = "src/day_1/main.rs"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]




